/*  Downloads every emoji the app actually uses as a Twemoji SVG and writes them
 *  into src/assets/icons/, plus an index module.
 *
 *  Why bundle instead of typing the character: system emoji render differently
 *  on every device — glossy on Windows, flat on Android, another shape again on
 *  iPhone — so the app has no consistent look of its own. Twemoji is flat and
 *  outline-free, which matches this UI, and ships at well under 1 KB apiece.
 *
 *  Twemoji graphics: CC-BY 4.0 (Twitter, now maintained at jdecked/twemoji).
 *  Attribution lives in README.md and on the settings screen.
 *
 *    node scripts/fetch-icons.mjs
 */
import { mkdirSync, readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs'
import { join, extname } from 'node:path'

const SRC = join(process.cwd(), 'src')
const OUT = join(SRC, 'assets', 'icons')
mkdirSync(OUT, { recursive: true })

/* Walk the source and collect every emoji character used. */
function walk(dir, files = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name)
    if (statSync(p).isDirectory()) walk(p, files)
    else if (['.js', '.jsx', '.css'].includes(extname(p))) files.push(p)
  }
  return files
}

// Pictographic characters, plus the keycap sequences (2️⃣) and variation
// selectors that make up a full emoji.
const EMOJI_RE =
  /(\p{Extended_Pictographic}(?:️)?(?:‍\p{Extended_Pictographic}(?:️)?)*|[0-9#*]️?⃣)/gu

const found = new Map()
for (const file of walk(SRC)) {
  const text = readFileSync(file, 'utf8')
  for (const m of text.matchAll(EMOJI_RE)) {
    const ch = m[0]
    if (!found.has(ch)) found.set(ch, [])
    found.get(ch).push(file.replace(process.cwd(), '.'))
  }
}

/** Twemoji filenames drop FE0F (the "render as emoji" hint) unless the sequence
    is only that, and join codepoints with dashes. */
const toName = (ch) => {
  const cps = [...ch].map((c) => c.codePointAt(0).toString(16))
  const kept = cps.length > 1 ? cps.filter((c) => c !== 'fe0f') : cps
  return (kept.length ? kept : cps).join('-')
}

const BASE = 'https://raw.githubusercontent.com/jdecked/twemoji/main/assets/svg'
const entries = []
let ok = 0
let missing = []

for (const ch of [...found.keys()].sort()) {
  const name = toName(ch)
  const url = `${BASE}/${name}.svg`
  try {
    const res = await fetch(url)
    if (!res.ok) {
      missing.push(`${ch} (${name}) HTTP ${res.status}`)
      continue
    }
    let svg = await res.text()
    // Strip the XML prolog; these get imported as components, not files.
    svg = svg.replace(/<\?xml[^>]*\?>\s*/g, '').trim()
    writeFileSync(join(OUT, `${name}.svg`), svg)
    entries.push({ ch, name })
    ok++
  } catch (e) {
    missing.push(`${ch} (${name}) ${e.message}`)
  }
}

/* An index that maps the emoji character to its imported URL, so calling code
   can keep writing the emoji it already writes. */
const lines = [
  '/* GENERATED by scripts/fetch-icons.mjs — do not edit by hand.',
  ' * Twemoji graphics, CC-BY 4.0 (https://github.com/jdecked/twemoji).',
  ' * Regenerate after adding a new emoji anywhere in src/. */',
  '',
  ...entries.map((e, i) => `import i${i} from './icons/${e.name}.svg'`),
  '',
  'export const ICONS = {',
  ...entries.map((e, i) => `  ${JSON.stringify(e.ch)}: i${i},`),
  '}',
  '',
]
writeFileSync(join(SRC, 'assets', 'icons.js'), lines.join('\n'))

const total = readdirSync(OUT).reduce((s, f) => s + statSync(join(OUT, f)).size, 0)
console.log(`✓ ${ok} icons, ${(total / 1024).toFixed(1)} KB total`)
if (missing.length) console.log('missing:', missing.join(' | '))
